name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  code:
    name: Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Test your example code here
