name: Slides

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  DAGGER_VERSION: 0.13.0

jobs:
  render:
    name: Render
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Pipeline
        uses: dagger/dagger-for-github@c69716804178d5dbc9cf4c2823d42a18f9284bd1 # v6.12.0
        with:
          version: ${{ env.DAGGER_VERSION }}
          verb: call
          module: github.com/sagikazarmark/daggerverse/quarto@cba5bd028da6c751e3bd95b662cf23f42ebd5806
          args: render --source="slides" --site-url ${{ steps.pages.outputs.base_url }} directory export --path="slides/_site"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./slides/_site

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false
    needs: render
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
